[package]
name = "tui-markup-sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

tui = "0.19.0"
tui-markup = { path = "../tui-markup" }
crossterm = "0.24.0"
